export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETILS_REQUEST = "PRODUCT_DETILS_REQUEST";
export const PRODUCT_DETILS_SUCCESS = "PRODUCT_DETILS_SUCCESS";
export const PRODUCT_DETILS_FAIL = "PRODUCT_DETILS_FAIL";
